config/routes.rb
Rails.application.routes.draw do
  root 'front_page#index'

  resources :projects, except: :show
  resources :contacts, only: [:new, :create]

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  validates :username, presence: true

  has_secure_password validations: false
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, :email, :body, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :description, :tech, :url, :image, presence: true

  mount_uploader :image, ProjectImageUploader

  def tech_array
    tech.nil? ? [] : tech.split(/,/).map { |e| e.delete(',').strip }
  end

  def complete_url
    return self.url if self.url.include?('http://')
    self.url.include?('www.') ? 'http://' + self.url : 'http://www.' + self.url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :admin, :admin_signed_in?, :require_admin

  def admin
    @admin ||= Admin.find(session[:admin_id]) if session[:admin_id]
  end

  def admin_signed_in?
    !!admin
  end

  def require_admin
    unless admin
      flash[:error] = 'You must be an admin to do that.'
      redirect_to root_path
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.create(contact_params)
    if @contact.save
      ContactsMailer.contact_email(@contact).deliver_later
      redirect_to root_path, notice: 'Your email was sent!'
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :body)
  end
end

app/controllers/front_page_controller.rb
class FrontPageController < ApplicationController
  def index;end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_admin, except: :index

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)

    if @project.save
      redirect_to projects_path, notice: 'Success! New project created.'
    else
      flash.now[:error] = 'Oops! Please fix the errors below.'
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to projects_path, notice: 'Success! Project updated.'
    else
      flash.now[:error] = 'Oops! Please fix the errors below.'
      render :edit
    end
  end

  def destroy
    project = Project.find(params[:id])
    project.destroy
    redirect_to projects_path, notice: 'Success! Project deleted.'
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :url, :tech, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new;end

  def create
    admin = Admin.find_by_username(params[:username])
    #require 'pry'; binding.pry
    if admin && admin.authenticate(params[:password])
      session[:admin_id] = admin.id
      redirect_to root_path, notice: 'Success! You are signed in.'
    else
      flash.now[:error] = 'Oops! Looks like your username or password were incorrect.'
      render :new
    end
  end

  def destroy
    session[:admin_id] = nil
    redirect_to root_path, notice: 'Success! You are signed out.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.haml
%h2 Contact Reed

= render 'shared/errors', object: @contact

.form_field
  = form_for @contact do |f|
    = f.text_field :name, placeholder: 'Name'
    = f.email_field :email, placeholder: 'Email'
    = f.text_area :body, placeholder: 'Message', size: '60x12'
    = f.submit 'Send Message'

app/views/front_page/index.html.haml
%section#home{"data-type" => "background", "data-speed" => ".5"}
  %h1 Reed Nelson-Saunders

%h2 Cool
%h2 Cool
%h2 Cool

%h2 Cool
%h2 Cool
%h2 Cool
%h2 Cool

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  -if msg.is_a?(String)
    %div(class="flash-#{name}")
      = msg
      = link_to 'Ok.', id:'close-flash'

app/views/layouts/_nav_bar.html.haml
%header.navigation
  .navigation-wrapper
    %a.logo{:href => "javascript:void(0)"}
      %img{:alt => "Logo Image", :src => "https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png"}/
    %a#js-mobile-menu.navigation-menu-button{:href => "javascript:void(0)"} MENU
    .nav
      %ul#js-navigation-menu.navigation-menu.show
        %li.nav-link
          %a.scroll-on-page-link= link_to 'About', root_path
        %li.nav-link
          %a.scroll-on-page-link= link_to "Projects", projects_path
        %li.nav-link
          %a.scroll-on-page-link= link_to 'Contact', new_contact_path
        / / %li.nav-link.more
        / /   %a{:href => "javascript:void(0)"} More
        / /   %ul.submenu
        / /     %li
        / /       %a{:href => "javascript:void(0)"} Submenu Item
        / /     %li
        / /       %a{:href => "javascript:void(0)"} Another Item
        / /     %li.more
        / /       %a{:href => "javascript:void(0)"} Item with submenu
        / /       %ul.submenu
        /         / %li
        /           %a{:href => "javascript:void(0)"} Sub-submenu Item
        /         %li
        /           %a{:href => "javascript:void(0)"} Another Item
        /     %li.more
        /       %a{:href => "javascript:void(0)"} Another submenu
        /       %ul.submenu
        /         %li
        /           %a{:href => "javascript:void(0)"} Sub-submenu
        /         %li
        /           %a{:href => "javascript:void(0)"} An Item
        - if !admin_signed_in?
          %li.nav-link
            %a.scroll-on-page-link.sign-in= link_to "Sign In", sign_in_path
        - else
          %li.nav-link
            %a.scroll-on-page-link.sign-in= link_to "Sign Out", sign_out_path, method: :delete
    / .navigation-tools
    /   .search-bar
    /     .search-and-submit
    /       %input{:placeholder => "Enter Search", :type => "search"}/
    /       %button{:type => "submit"}
    /         %img{:alt => "Search Icon", :src => "https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png"}/
    /   %a.sign-up{:href => "javascript:void(0)"} Sign Up

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ReedPortfolio
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/nav_bar'
    = render 'layouts/messages'
    = yield

app/views/projects/_form.html.haml
= render 'shared/errors', object: @project

.form_field
  = form_for(@project) do |f|
    = f.text_field :name, placeholder: 'Project name'
    = f.text_field :tech, placeholder: 'Technologies used'
    = f.text_field :url, placeholder: 'Project URL'
    = f.file_field :image, placeholder: 'Project image'
    = f.text_area :description, placeholder: 'Project description', size: '60x12'
    = f.submit @project.new_record? ? 'Create' : 'Update'
    = button_to 'Cancel', projects_path, class: "cancel" unless @project.new_record?

app/views/projects/edit.html.haml
%h3 Edit Project
= render 'form'

app/views/projects/index.html.haml
.cards
  - @projects.each do |project|
    .card
      .card-image
        %img{:alt => "", :src => "#{project.image}"}/
      .card-header
        = project.name
      .card-copy
        %p= project.description
        %p= link_to "#{project.url}", project.complete_url
      .card-stats
        %ul
          - project.tech_array.each do |tech|
            %li
              = tech
          -if admin_signed_in?
            %li
              = link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?'}, class: 'action'
            %li
              = link_to 'Edit', edit_project_path(project), class: 'action'

= link_to "New Project", new_project_path, class: 'new-project' if admin_signed_in?

app/views/projects/new.html.haml
%h3 New Project
= render 'form'

app/views/shared/_errors.html.haml
- if object.errors.any?
  %div.flash-error
    %h5 Please fix these errors:
    - object.errors.full_messages.each do |msg|
      %ul
        %li= msg